const { fetchMemories, summarizeMemories } = require('../../utils/memoryHelper');

const analyzeModel = async (target, author, conversation) => {
	const firstMessageVector = conversation[0].vector;
	const previousMessages = conversation.slice(1);
	// choose the top 10 matches
	const topMatchAmount = 10;
	const memories = await fetchMemories(firstMessageVector, previousMessages, topMatchAmount);
	const notes = await summarizeMemories(memories);
	const recent = [...conversation].slice(-4).map(m => m.message).join('\n\n');

	return `The following is a conversation with Senti, an expert in teaching emotional intelligence and social skills. Senti is helpful, creative, clever, and very friendly. Senti is a master in emotional intelligence and navigating social situations. Senti gives long elaborate, verbose and detailed answers to all social questions.\n\nHuman:The following are notes from earlier conversations with ${author} and ${target}:\n${notes}\n\nThe following are the most recent messages in the conversation:\n${recent}\n\nAnalyze the content and tone of the conversation between ${author} and ${target}, and provide feedback on strengths and weaknesses in ${author}'s communication. If there are no clear strengths just say "there are no clear strengths", if there are no clear weaknesses just say "there are no clear weaknesses"\n\nSenti:`;
};

exports.analyzeModel = analyzeModel;

// \n\nHuman: Analyze the content and tone of the conversation between human1 and human2 below, and provide feedback on strengths and weaknesses in human1's communication. If there are no clear strengths just say "there are no clear strengths", if there are no clear weaknesses just say "there are no clear weaknesses":\nhuman1\nDo you still play tarkov?\nhuman2\ni havent played for a bit to be honest. Why? whats up?\nhuman1\nWas thinking about buying it but not sure haha.\nIn 8 days the call of duty version comes out.\nhuman2\nwhat do you mean by the call of duty version? i havent been keeping up with the game all that much\n human1\nLooter shooter version of call of duty called DMZ comes out for free.\nhuman2\noh... that seems cool.. and that comes out on the 15th?\nhuman1\n16th!\nhuman2\nt i can math\nsometimes\nhuman1\nLololol\nDecember 16th is the next dark and darker playtest. I can't wait for that. The game is so addicting.\nhuman2\nTarkov was the same way… I personally think they ruined the game with all the realistic aspects they added like inertia and other odd things\n\nSenti: In the conversation provided, human1 seems to be enthusiastic about the game Tarkov, and considering buying it. He also shares an upcoming event related to the game with human2, and expresses excitement for the new version of Call of Duty. human1 also has a light-hearted and friendly tone throughout the conversation, which can help to build rapport with human2.\nOne strength in human1's communication is that he is able to initiate a conversation and share information with human2, which can be helpful in building a connection and showing interest in human2's interests. Additionally, human1 is able to maintain a friendly and light-hearted tone throughout the conversation, which can help to make the conversation more enjoyable and relaxed.\nOne potential weakness in human1's communication is that he does not seem to be actively listening to human2's responses. human2 mentions that he has not played Tarkov for a while and is not aware of the new version of Call of Duty, but human1 does not seem to address these points. Additionally, human1 does not seem to acknowledge or respond to human2's comment about Tarkov being ruined with the addition of realistic aspects like inertia.\nOverall, human1 demonstrates good social skills and emotional intelligence in his communication with human2, he is friendly, enthusiastic, and able to initiate a conversation. However, he could benefit from actively listening and acknowledging human2's responses and perspective on the game.
